name: Build Plugin

on:
  push:
    branches: [ main ]
    
#  workflow_dispatch:
#    inputs:
#      build_configuration:
#        description: 'Build configuration'
#        default: 'Release'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/download-artifact@v2
    
    - name: Download Valheim
      run: |
        dotnet contrib/depotdownloader-2.5.0/DepotDownloader.dll -app 896660 -os windows -filelist .depot-downloader-file-list.txt -dir serverfiles
    
    - name: Publicize assembly
      run: |
        cd serverfiles/valheim_server_Data/Managed
        ../../../contrib/AssemblyPublicizer/AssemblyPublicizer.exe -i assembly_valheim.dll -o ./assembly_valheim_publicized.dll
        
    - name: build
      run: |
        xcopy /E /I lib ..\ValheimLibs
        xcopy /I serverfiles\valheim_server_Data\Managed\* ..\ValheimLibs\
        msbuild /t:Restore,Build -p:Configuration=Release
        
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: serverside-simulations-${{ github.sha }}
        path: bin\Release\Serverside_Simulations.dll

      
